ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mySite.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mySite/urls.py
from django.urls import path
from . import views

app_name = "mySite"
urlpatterns = [
    path("", views.store, name="store"),
    path("cart/", views.cart, name="cart"),
    path("checkOut/", views.checkOut, name="checkOut"),
    path("update_item/", views.updateItem, name="update_item"),
    path("process_order", views.processOrder, name="process_order"),
    path("register/", views.register, name="register"),
    path("login/", views.loginProcess, name="login"),
]

mySite/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(
        User, null=True, blank=True, on_delete=models.DO_NOTHING
    )
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=200, null=True)


class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True
    )
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def cart_items(self):
        items = self.orderitem_set.all()
        total = sum([item.quantity for item in items])
        return total


class orderItem(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, blank=True, null=True
    )
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class shippingAddress(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True
    )
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=500)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    zipcode = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

mySite/views.py
from django.shortcuts import render, redirect
from .models import *
from django.http import JsonResponse
import json
from .models import Customer
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def loginProcess(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, "mySite/store.html")
        else:
            messages.info(request, "Username or password is incorrect")
    else:
        return render(request, "mySite/login.html")


def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            new_user = Customer.objects.get_or_create(user=request.user)
            return render(request, "mySite/store.html")

    context = {"form": form}
    return render(request, "mySite/register.html", context)


def store(request):
    products = Product.objects.all()
    context = {"products": products}
    return render(request, "mySite/store.html", context)


def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
    else:
        items = []
        order = {"cart_total": 0, "cart_items": 0}
    context = {"items": items, "order": order}
    return render(request, "mySite/cart.html", context)


def checkOut(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
    else:
        items = []
        order = {"cart_total": 0, "cart_items": 0}
    context = {"items": items, "order": order}
    return render(request, "mySite/checkOut.html", context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data["productId"]
    action = data["action"]

    print("action: ", action)
    print("productId: ", productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderitem, created = orderItem.objects.get_or_create(order=order, product=product)

    if action == "add":
        orderitem.quantity = orderitem.quantity + 1
    elif action == "remove":
        orderitem.quantity = orderitem.quantity - 1

    orderitem.save()
    if orderitem.quantity <= 0:
        orderitem.delete()

    return JsonResponse("Item added", safe=False)


def processOrder(request):
    print(request.body)
    return JsonResponse("COmplete", safe=False)

mySite/templates/mySite/cart.html
{% extends 'mySite/main.html' %}
{% load static %}

{% block content %}
<div class='row'>
    <div class='col-lg-12'>
        <div class='box-element'>
            <a class='btn btn-outline-dark' href="{% url 'mySite:store' %}">&#8592; Continue Shopping</a>
        </div>
        <br>
        <br>
        <table class='table'>
            <tr>
                <th><h5>Items: <strong>{{order.cart_items}}</strong></h5></th>
						<th><h5>Total:<strong> Rs {{order.cart_total|floatformat:2}}</strong></h5></th>
                <th><a style='float:right;margin:5px' class='btn btn-success' href="{% url 'mySite:checkOut' %}">Checkout</a></th>
            </tr>
        </table>

    </div>
    <br>
    <div class='box-element'></div>
    <div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.image.url}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>Rs {{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.svg' %}">

							<img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.svg' %}">
						</div>
					</div>
					<div style="flex:1"><p>Rs {{item.get_total|floatformat:2}}</p></div>
				</div>
				{% endfor %}
    </div>
</div>

{% endblock content %}

mySite/templates/mySite/checkOut.html
{% extends 'mySite/main.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form id="info">
                <div id="user-info">
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Name">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="email" name="email" placeholder="Email">
                    </div>
                </div>

                <div id="shipping-info">
                    <hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Country">
						</div>

                </div>
                <hr>
                <input id='form-buttom' class="btn btn-success" type="submit" value="Continue"></input>
            </form>
        </div>
        <br>
        <div class="box-element " id="payment-info">
				<small>Payment Options</small>
				<div id="paypal-button-container"></div>
			</div>
    </div>
    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'mySite:cart' %}">Back to cart</a>
        <hr>
        <h4>Summery</h4>
        <hr>
       {% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.image.url}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>Rs {{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1"><p>x{{item.quantity}}</p></div>
				</div>
				{% endfor %}
				<h5>Items:   {{order.cart_items}}</h5>
				<h5>Total:   Rs {{order.cart_total|floatformat:2}}</h5>
        </div>
    </div>
</div>

<script type="text/javascript">
    let from=document.getElementById('form')
    form.addEventListener('submit',function(e){
        e.preventDefault();
    });

    function submitForm(){
        var userData={
            'name':form.name.value,
            'email':form.email.value
        }

        let shippingForm={
            'address':form.address.value,
            'city':form.city.value,
            'state':form.state.value,
            'zipcode':form.zipcode.value,
            'country':form.country.value,
        }
        var url='/process_order/'
        fetch(url,{
            method='POST',
            headers:{
                'Content-Type': 'application/json',
                'X-CSRFToken':csrftoken,
            },
            body:JSON.stringify({'user':userData,'address':shippingForm})
        }).then((response) => {
      return response.json();
    })
        .then((data) => {
            console.log('sent');
            alert('Transaction Complete');
            window.location.href="{% url 'mySite:store' %}"

        }

    }




</script>
{% endblock content %}

mySite/templates/mySite/login.html
{% extends 'mySite/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<form method='post'>
    {% csrf_token %}
    <div class="mb-3">
      <label for="username" class="form-label">UserName</label>
      <input type="text" class="form-control" id="username" name="username" >      
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input type="password" class="form-control" id="password" name="password">
    </div>    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

mySite/templates/mySite/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Ecommerce</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script src="js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <script type="text/javascript">
        function getToken(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		var csrftoken = getToken('csrftoken')
    </script>



</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'mySite:store' %}">Ecom</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'mySite:cart' %}">Cart</a>
        </li>
      </ul>
      <div class="form-inline my-2 my-lg-0">
	     	

	     	<a href="{% url 'mySite:cart' %}">
	    		<img  id="cart-icon" src="{% static 'images/cart.jpg' %}">
	    	</a>
	    	<p id="cart-total">{{cartItems}}</p>

	    </div>
	  </div>
</nav>

<div class="container">
    {% block content %}
    {% endblock content %}
</div>



<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

</body>
</html> 

mySite/templates/mySite/register.html
{% extends 'mySite/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post">
    {% csrf_token %}
  {{form|crispy}}  
    <input type='submit'>
</form>
{% endblock %}

mySite/templates/mySite/store.html
{% extends 'mySite/main.html' %}
{% load static %}

{% block content %}
	<div class="row">
		{% for product in products %}
		<div class="col-lg-4">
			<img class="thumbnail" src="{{product.image.url}}">
			<div class="box-element product">
				<h6><strong>{{product.name}}</strong></h6>
				<hr>

				<button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>

				<a class="btn btn-outline-success" href="#">View</a>
				<h4 style="display: inline-block; float: right"><strong>Rs {{product.price}}</strong></h4>

			</div>
		</div>
		{% endfor %}
	</div>

{% endblock content %}